---
- name: Install cups and extras
  ansible.builtin.package:
    name: "{{ item }}"
  with_items: "{{ ['cups'] + extra_printer_driver_packages }}"

- name: Ensure cups is running and enabled
  ansible.builtin.service:
    name: "cups"
    state: started
    enabled: true

- name: Add '{{ ansible_facts.user_id }}' to lpadmin group
  ansible.builtin.user:
    name: "{{ ansible_facts.user_id }}"
    groups: lpadmin
    append: yes
  notify: restart cups

- name: Setup cups config
  ansible.builtin.template:
    src: cupsd.conf.j2
    dest: /etc/cups/cupsd.conf
    mode: "0640"
    validate: cupsd -t -c %s
  notify: restart cups
