- name: Install samba packages
  ansible.builtin.package:
    name:
      - samba
      - samba-common-bin

- name: Config printer sharing
  ini_file:
    path: /etc/samba/smb.conf
    section: printers
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items: "{{ samba_printer_sharing.config.printers }}"

- name: Config printer driver sharing
  ini_file:
    path: /etc/samba/smb.conf
    section: "print$"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items: "{{ samba_printer_sharing.config['print$'] }}"

- name: Ensure samba is running and enabled
  ansible.builtin.service:
    name: smbd
    state: started
    enabled: true
  notify: restart samba
