---
yaml-files:
  - "*.yaml"
  - "*.yml"
  - ".yamllint"

extends: default

rules:
  truthy:
    allowed-values: ["true", "false", "yes", "no"]
    check-keys: true
  comments:
    min-spaces-from-content: 1
