---
- name: Update and upgrade packages
  ansible.builtin.import_playbook: update.yaml

- hosts: print_server
  roles:
    - role: raspi-config
      become: true
      vars:
        ipv6: false

- hosts: print_server
  roles:
    - role: ssh
      become: true

- hosts: print_server
  roles:
    - role: net
      become: true

- hosts: print_server
  roles:
    - role: cups
      become: true

- name: Install HP M1132MFP
  ansible.builtin.import_playbook: m1132mfp.yaml

- name: Install Samsung ML-1660
  ansible.builtin.import_playbook: ml1660.yaml
