---
- name: Update and upgrade packages
  ansible.builtin.import_playbook: update.yaml

- hosts: print_server
  roles:
    - role: pi
      become: true
    - role: ssh
      become: true
    - role: cups
      become: true
