---

- name: Configure sshd options in /etc/ssh/sshd_config
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    # yamllint disable-line rule:truthy
    backup: yes
  with_items:  "{{ sshd_config_options }}"
  notify: restart sshd
  tags:
    - net
    - security
