---
- name: Disable wireless power management
  ansible.builtin.lineinfile:
    dest: /etc/rc.local
    line: /sbin/iw dev wlan0 set power_save off
    insertbefore: "^exit"
  when: ansible_facts.default_ipv4.interface is match("wlan*")
  tags:
    - net
    - wireless

- name: Set GPU memory to minimum
  ansible.builtin.lineinfile:
    dest: /boot/config.txt
    line: gpu_mem=16
    insertafter: "^[all]"
  tags:
    - raspi_config

- name: Check wait for network on boot
  ansible.builtin.command: raspi-config nonint get_boot_wait
  register: wait_for_network
  changed_when: false # Only reads "state"
  failed_when: wait_for_network.stderr != ""
  tags:
    - raspi_config

- name: Wait for network on boot
  ansible.builtin.command:
    cmd: raspi-config nonint do_boot_wait 0
  when: wait_for_network.stdout != "0"
  tags:
    - raspi_config

- name: Check unpartitioned fs space
  ansible.builtin.shell: |
    set -o pipefail
    /sbin/parted /dev/mmcblk0 unit gb print free \
      | grep 'Free Space' | tail -n1 | awk '{print $3}'
  args:
    executable: /bin/bash
  register: unpartitioned_space
  changed_when: false
  failed_when: unpartitioned_space.stderr != ""

- name: Expand filesystem
  ansible.builtin.command: raspi-config --expand-rootfs
  when: unpartitioned_space.stdout != "0.00GB"
  tags:
    - raspi_config

- name: Configure dhcpcd
  ansible.builtin.blockinfile:
    dest: /etc/dhcpcd.conf
    backup: yes
    block: |
      interface {{ ansible_facts.default_ipv4.interface }}
      static ip_address={{ ansible_facts.default_ipv4.address }}/24
      static routers={{ ansible_facts.default_ipv4.gateway }}
      static domain_name_servers={{ dns_servers }}
    insertafter: EOF
  notify: restart dhcpcd
  tags:
    - net

- name: Start the dhcpcd service
  ansible.builtin.service:
    name: dhcpcd
    state: started
    enabled: yes
  tags:
    - net

- name: Disable bluetooth in boot config
  ansible.builtin.lineinfile:
    dest: /boot/config.txt
    line: dtoverlay=disable-bt
    insertbefore: EOF
  when: not use_bluetooth
  tags:
    - io
    - bluetooth

- name: Disable hciuart service
  ansible.builtin.service:
    name: hciuart
    state: stopped
    enabled: no
  when: not use_bluetooth
  tags:
    - io
    - bluetooth
