name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0

      - name: prettier
        uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --write **/*.{ya?ml,json,md}
          commit_message: 'chore(auto): formatting'

  ansible-lint:
    runs-on: ubuntu-latest
    container:
      image: pipelinecomponents/ansible-lint:0.39.1
      volumes:
        - ${{ github.workspace }}:/code
    needs: formatting
    steps:
      # TODO: add problem matchers
      # TODO: parametrise this with project name
      - run: git config --global --add safe.directory /__w/ansible-gutenberg-pi/ansible-gutenberg-pi
      - uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
      - name: Lint Ansible roles
        run: |
          for roles in $(find ./roles/* -type d -maxdepth 0); do
            ansible-lint $roles;
          done;
      - name: Lint Ansible playbooks
        run: |
          for playbook in $(find . -type f -not -path '*/\.git/*' -name '*.yaml' -maxdepth 1); do
            ansible-lint $playbook;
          done;
  